### ISSUE TITLE
Installed FFOS Make ST2 Crashed

### ISSUE THREAD

**Issue by pije76** [miguelgraz/FocusFileOnSidebar#10]
I installed FFOS on Ubuntu 12.04 by using PPA and it make ST2 crashed.
I can't uninstall any packages or install new packages at all.
I've deleted FFOS folder inside Packages folder and it still not work.

**Comment by miguelgraz** [comment]
Sorry @pije76, I wasn't able to find a way to make it work with ST2, I'll drop support for ST2 until further notice :disappointed:
