### ISSUE TITLE
Side bar is hidden when no open files are open  

### ISSUE THREAD

**Issue by ogavrisevs** [miguelgraz/FocusFileOnSidebar#12]
When no files are opened and i press ⌘+K, ⌘+F side bar is hidden. 
This start to happen after update to build 3080 
Previously behaviour was cursor focused on first item in side bar.

**Comment by ogavrisevs** [comment]
for some reason "close_sidebar_if_opened": false," is not working for me ?

**Comment by ptim** [comment]
known issue: https://github.com/miguelgraz/FocusFileOnSidebar/issues/11, workaround: 

> While waiting for a new build, you can use PackageResourceViewer to open up FocusFileOnSidebar and modify FocusFileOnSidebar.py.

**Comment by miguelgraz** [comment]
Hello @ogavrisevs, thanks for taking the time to report it, it should be fixed now on https://github.com/miguelgraz/FocusFileOnSidebar/commit/c438e849f53829a8b00ca471d67b1a2ec7bb315b

Thanks @ptim for your comment here as well :)

Please test it now and feel free to reopen this issue if necessary.

Thank you! :snowboarder:
