### ISSUE TITLE
Keep sidebar folder opened

### ISSUE THREAD

**Issue by missoxd** [miguelgraz/FocusFileOnSidebar#15]
Hi,

When i am on a file inside a folder and press Cmd+K+F it keeps the folder where my file is opened, normal behavior.

But, for example, when i change to a file on the root folder, and then reopen the sidebar with Cmd+K+F it will close all folders that were opened on the sidebar.

It would be nice to have an option to keep the state of the sidebar.

Thank you.

**Comment by ptim** [comment]
known issue: https://github.com/miguelgraz/FocusFileOnSidebar/issues/11, workaround: 

> While waiting for a new build, you can use PackageResourceViewer to open up FocusFileOnSidebar and modify FocusFileOnSidebar.py.

**Comment by miguelgraz** [comment]
Hello @missoxd, thanks for taking the time to report it, it should be fixed now on https://github.com/miguelgraz/FocusFileOnSidebar/commit/c438e849f53829a8b00ca471d67b1a2ec7bb315b

Thanks @ptim for your comment here as well :)

Please test it now and feel free to reopen this issue if necessary.

Thank you! :snowboarder:
