### ISSUE TITLE
No works with __init__ files

### ISSUE THREAD

**Issue by jairomtzant** [miguelgraz/FocusFileOnSidebar#17]
*Hi Miguel,*

Currently the plugin is not working with __init_.py. :)

Many thanks for your time developing this plugin.

**Comment by miguelgraz** [comment]
Hello Jairo!

Sorry I'm not quite a Python expert and therefore I didn't really follow the problem you reported, what do you mean by "not working with `__init__.py`? Can you provide more information?

Thank you for taking the time to report the problem, I really hope I can fix it for you :smile:

**Comment by jairomtzant** [comment]
**Hi Miguel,**

Thanks to you for your prompt response.

In fact I was reviewing another SublimeText...

Stop :) I am opening the project again to take some screenshots, but I cannot reproduce the "issue". I promise, yesterday for __init__ files the plugin was not highlight the respective in the SideBar:
![Issue__init__py](https://cloud.githubusercontent.com/assets/5806694/9470250/b99ea6aa-4b10-11e5-9860-35bb23c3f4f1.png) 

An apologize for this report but I am sure about the issue :)

Have a nice day Miguel.

**Comment by miguelgraz** [comment]
Oh you meant for files named `__init__.py`, I see now!

I haven't tested this case, will try to reproduce it locally as well, and if you run into this problem again please feel free to reopen this issue :smile_cat: 

Again thanks for your time reporting it!

Cheers! :snowboarder:
