### ISSUE TITLE
Focus lost after closing sidebar

### ISSUE THREAD

**Issue by it6** [miguelgraz/FocusFileOnSidebar#22]
Thanks for this package, I find it super helpful. 

I noticed a minor issue, once I reveal the file in sidebar `Cmd-k Cmd-f`, then I close the sidebar using `Cmd-k Cmd-f` I loose focus of my caret on the current file. See below for details. I would like to retain focus back to editor, instead of pressing one extra `escape`.

![focus_sidebar](https://user-images.githubusercontent.com/5510191/36402765-d284d2d2-15ae-11e8-812e-3bc8cc026eb7.gif)

**Comment by miguelgraz** [comment]
Hey @it6! Thanks for your kind words and for taking the time to report this! And sorry for taking so long to get back to you here.

I can definitely reproduce and confirm the issue, perhaps other users just hit `enter` when they find the desired file in sidebar, which takes the focus back to the editor but keep the sidebar open, this one use case you mentioned indeed has the reported issue. Now moving to the PR :smiley:

**Comment by miguelgraz** [comment]
Fixed on https://github.com/miguelgraz/FocusFileOnSidebar/pull/23 thanks to @it6 :fist_raised:
