### ISSUE TITLE
Crashes ST2 on uninstall

### ISSUE THREAD

**Issue by sogen** [miguelgraz/FocusFileOnSidebar#5]
Hi, disabling it or removing it causes ST2 to crash.
How can I uninstall it?
btw, there's a comma error in console:
```
Error loading commands: Error trying to parse file: Trailing comma before closing bracket in C:\Users\myusername\Documents\myUsername\Software\s2\Data\Packages\Focus File on Sidebar\Default.sublime-commands:5:3
```

**Comment by miguelgraz** [comment]
Sorry folks, I wasn't able to find a way to make it work with ST2, I'll drop support for ST2 until further notice :disappointed:
