### ISSUE TITLE
Change handlers are leaking and causing memory leaks

### ISSUE THREAD

**Issue by rahul-ramadas** [miguelgraz/FocusFileOnSidebar#6]
In `plugin_loaded`, you install change handlers, but you never remove them. Also, whenever you get a change callback, you install another handler. This has an exponential effect, because you double the number of registered callbacks each time (you can have multiple callbacks per key).

You can reproduce this issue if you have another plugin that modifed the 'Preferences.sublime-settings' file in-memory. You won't be able to repro the issue simply by changing the settings on-disk, because that doesn't trigger the change handler (or maybe it does sporadically, not really sure).

Tips:

1. Remove change handlers in `plugin_unloaded` for ST3.
2. Don't install the change handler again on a change.

**Comment by miguelgraz** [comment]
Hey @rahul-ramadas, I tried to fix that with a simple change, would you mind to take a look and review it for me? It lives on https://github.com/miguelgraz/FocusFileOnSidebar/compare/leak

Thanks in advance! :snowboarder:

**Comment by miguelgraz** [comment]
So after lots of pertinent reviews and learned things from @rahul-ramadas this bug was fixed and the master branch just updated! :snowboarder: 

All credit to @rahul-ramadas, thank you very much for all patience and tips, I learned a lot. :heart:
