### ISSUE TITLE
Command focus_file_on_sidebar closes sidebar when not expected

### ISSUE THREAD

**Issue by elado** [miguelgraz/FocusFileOnSidebar#7]
First - awesome plugin, I've been looking for something like this.

The behavior is unexpected -- when sidebar is opened and I'm on a file and activate the focus_file_on_sidebar command, it closes the sidebar.
When I activate again - it opens the sidebar.
In some cases, the sidebar opens with the entire tree closed.

When it works, occasionally, it closes all the tree but the actual file. I'd expect it to just focus on the file and let me navigate from there with keyboard.

Thanks!

**Comment by miguelgraz** [comment]
Trying to make it up to any possible user here I am reviewing the issues, will close this for now, if anything is still broken or the `close_sidebar_if_opened` option didn't work as expected please feel free to reopen it :snowboarder:
